name: novel-echoes-dev

services:

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./var/postgres/data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  
  elasticsearch:
    build: 
      context: .
      dockerfile: elasticsearch.Dockerfile
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
      http.port: 9200
      transport.host: localhost
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      TAKE_FILE_OWNERSHIP: 1
      ELASTIC_PASSWORD: "elastic"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./var/elasticsearch/data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  symfony:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - "8080:8000"
    volumes:
      - ./app:/app
    depends_on:
      - postgresql
      - elasticsearch
  
  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: node-dev
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
