wouterj_eloquent:
    driver:   '%env(DATABASE_DRIVER)%'
    host:     '%env(DATABASE_HOST)%'
    port:     '%env(DATABASE_PORT)%'
    database: '%env(DATABASE_NAME)%'
    username: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
    # Uncomment the following line to enable the Eloquent ORM
    eloquent: null